version: "3.9"
services:
  app:
    build: ./app
    container_name: tablecrm_app
    ports: ["8000:8000"]
    networks: [net]
  prometheus:
    image: prom/prometheus:latest
    container_name: tablecrm_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    depends_on: [app]
    networks: [net]
  grafana:
    image: grafana/grafana:latest
    container_name: tablecrm_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports: ["3000:3000"]
    depends_on: [prometheus]
    networks: [net]
networks:
  net: { driver: bridge }
